use_frameworks!

target 'FSNetworkKit_Example' do
  pod 'FSNetworkKit', :path => '../'

  target 'FSNetworkKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
